### ISSUE TITLE
Replace installed sqlite DB with alternate version in assets folder

### ISSUE THREAD

**Issue by tellypresence** [daolq3012/AssetSQLiteOpenHelper#3]
I'm looking for an alternative to `Android SQLiteAssetHelper` (https://github.com/jgilfelt/android-sqlite-asset-helper) since that project is no longer maintained and so won't be updated for modern `SupportSQLite*` workflow.

My usecase is that I ship my app with multiple sqlite databases in the `assets` folder, and the user
can completely replace one with another at the touch of a button (obviously the DBs are structurally identical, it's just that they're populated with different data).  This was working well thanks to good support community and documentation with `Android SQLiteAssetHelper` so was wondering if this is also feasible using this project?

Note that I don't care about DB migrations, just need to be able to completely replace an installed
sqlite DB, with another from assets, on-the-fly.

**Comment by daolq3012** [comment]
@tellypresence 
I will try!

**Comment by tellypresence** [comment]
On further consideration I don't think this feature would be useful to many people,
please close this issue.
