### ISSUE TITLE
Allow overriding databases folder under assets

### ISSUE THREAD

**Issue by tellypresence** [daolq3012/AssetSQLiteOpenHelper#4]
For android app bundles, it's possible to configure subfolders so they are ignored depending on
languages.  For example, if we had
```
assets/database#lang_en/mydb.db
assets/database#lang_fr/mydb.db
assets/database#lang_es/mydb.db

```
and created an android app bundle instead of an apk, the downloadable apk would only contain
the .db file corresponding to the language set on the user's device (that's the theory, anyway)

Obviously, this will be a bit hacky when developing in non-release mode i.e. deploying apk directly
to usb connected device via adb, as is usual during development.

The point is, it would be very useful if there could be an extra parameter added in order
to override the default "databases" folder name e.g.
```
dbInstance = Room.inMemoryDatabaseBuilder(context, MyDB::class.java)
    .openHelperFactory(AssetSQLiteOpenHelperFactory("database#lang_es"))
```
so developers could control the folder name for debug (via apk) and release (via abb) builds.

**Comment by daolq3012** [comment]
Resolve in https://github.com/daolq3012/AssetSQLiteOpenHelper/pull/7
Has public in version 1.0.1
