### ISSUE TITLE
Jitpack build not available for 1.0.1

### ISSUE THREAD

**Issue by tellypresence** [daolq3012/AssetSQLiteOpenHelper#8]
Release "1.0.1" not available from jitpack for some reason
https://jitpack.io/com/github/daolq3012/AssetSQLiteOpenHelper/1.0.1/build.log
`No build artifacts found`

Release "V1.0.1" (note the 'V', older version) is available
https://jitpack.io/com/github/daolq3012/AssetSQLiteOpenHelper/V1.0.1/build.log
`Found artifact: com.github.daolq3012:library:V1.0.1`

Note: release 1.0.0 similarly unavailable, details:
https://jitpack.io/#com.github.daolq3012/AssetSQLiteOpenHelper

**Comment by daolq3012** [comment]
@tellypresence 
I just update readme V1.0.1
